### PR TITLE
Update Yytoken.java

### PR DESCRIPTION
**Pull request by dbogancs2**
Is it ok mate?

### CODE REVIEW

**Review by bme-student-2016 — CHANGES_REQUESTED** [review]
What do you think?? This fix is terrible! Go back and do something else...

**Comment by dbogancs2** [comment]
Is it better now, master?

**Comment by dbogancs** [comment]
Yes, this is acceptable.

**Review by bme-student-2016 — APPROVED** [review]
This is acceptable now

**Pull request merged**
